language: node_js
node_js:
  - "6.1"
install:
  - npm install -g bower
  - npm install -g polymer-cli
before_script:
  - bower install
script:
  - polymer build
before_deploy:
  - npm install -g firebase-tools
deploy:
  provider: firebase
  token: "${FIREBASE_TOKEN}"
  project: "${FIREBASE_PROJECT_ID}"
  on:
    branch: master
